namespace: caresync
image:
  repository: nandana2002/caresync-auth
  tag: latest
  pullPolicy: Always
service:
  name: caresync-auth-service
  port: 4001
  type: ClusterIP
replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
healthPath: /health
