apiVersion: v1
kind: Secret
metadata:
  name: caresync-secrets
  namespace: {{ .Values.namespace }}
  labels:
    project: caresync
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
